name: Firebase tmp deploy

run-name: Tmp deploy on {{ github.repository }}

on: 
  pull_request:
    branches:
      - develop

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GHW_CLOUD_25 }}"
          expires: 5d
          projectId: your-Firebase-project-ID